# Generated by Django 4.2.3 on 2024-03-28 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "usersignup_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("AdminId", models.CharField(max_length=25)),
            ],
            options={
                "abstract": False,
            },
            bases=("client.usersignup",),
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "usersignup_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("DocId", models.CharField(max_length=25)),
            ],
            options={
                "abstract": False,
            },
            bases=("client.usersignup",),
        ),
        migrations.CreateModel(
            name="MedicalPractitioner",
            fields=[
                (
                    "usersignup_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("MedId", models.CharField(max_length=25)),
            ],
            options={
                "abstract": False,
            },
            bases=("client.usersignup",),
        ),
    ]
